language: ruby
sudo: false
os:
- osx
- linux
cache: bundler
branches:
  only: master
script: TESTOPTS=-v bundle exec rake $TASK
env:
- TASK=test
before_install: ruby -e "File.write('Gemfile.lock', File.read('Gemfile.lock').split('BUNDLED WITH').first)"
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
matrix:
  include:
  - rvm: 2.3 # keep in sync with lowest version
    env: TASK=rubocop
  allow_failures:
  - os: linux
  fast_finish: true
